
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jzgfijvohytbcrtnagqy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp6Z2ZpanZvaHl0YmNydG5hZ3F5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwOTQ0MTgsImV4cCI6MjA2NTY3MDQxOH0.CbT4iB_nNg_q1WS93FqYZrBD-FoJ5Kd8K7RPTrLa55Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    headers: {
      'x-client-info': 'lovable-app@1.0.0',
    },
  },
});

// Add connection test for debugging
supabase.from('products').select('count', { count: 'exact', head: true })
  .then(({ error, count }) => {
    if (error) {
      console.error('Supabase connection test failed:', error);
    } else {
      console.log('Supabase connection successful, products count:', count);
    }
  });
